FROM jupyter/base-notebook:ubuntu-18.04

RUN conda install mamba -y --quiet -c conda-forge

# install root via mamba
RUN mamba install -y --quiet \
	root \
    && conda clean --all

# packages not in conda
RUN pip install --no-cache-dir \
        uproot \
        uproot3 \
        awkward \
        pandas \
        numpy \
        matplotlib \
        lmfit \
        scikit-learn \
        vector \
        tflearn
